// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmAeEniwbkkluiSLAyV4wjDiDTEGAEp4',
    appId: '1:875119458753:web:c9b5a5dff847d3d1a75740',
    messagingSenderId: '875119458753',
    projectId: 'mytodo-app-final',
    authDomain: 'mytodo-app-final.firebaseapp.com',
    storageBucket: 'mytodo-app-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_bhjulWF8eY3wpmXLwiVvxffwowRsiR0',
    appId: '1:875119458753:android:7e9dd4a4138d73e7a75740',
    messagingSenderId: '875119458753',
    projectId: 'mytodo-app-final',
    storageBucket: 'mytodo-app-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHaDoKMWASVpACuHOR93eaUAGEPLxLYY',
    appId: '1:875119458753:ios:b20e86e88c705e0ca75740',
    messagingSenderId: '875119458753',
    projectId: 'mytodo-app-final',
    storageBucket: 'mytodo-app-final.appspot.com',
    iosClientId: '875119458753-nrf2kjimqpt5brb13ml1q6et0k1nap5t.apps.googleusercontent.com',
    iosBundleId: 'com.piotrpeczkowski.myTodoApp',
  );
}
